[[news]]
date = "2026-07"
content = "AOT* was published in Findings of ACL 2026."

[[news]]
date = "2026-06"
content = "Towards Principled Task Grouping for Multi-Task Learning was accepted by TMLR."

[[news]]
date = "2026-01"
content = "Beyond the Heatmap was accepted to ICLR 2026."
